# Generated by Django 2.2.17 on 2020-12-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lessons',
            field=models.ManyToManyField(to='lesson.Lesson'),
        ),
    ]
