# Generated by Django 2.2.17 on 2020-12-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lessons',
            field=models.ManyToManyField(related_name='students', to='lesson.Lesson'),
        ),
    ]
